package DIV.credit.client.io;

import DIV.credit.Credit;
import DIV.credit.client.draft.RecipeDraft;
import net.minecraft.client.Minecraft;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * KubeJS .js ファイルへの追記/新規作成。
 * カテゴリごとに 1 ファイル、マーカー優先 → `});` 直前 → 連番ファイルの三段フォールバック。
 */
public final class ScriptWriter {

    public static final String MARKER = "// @credit:insert-marker";
    public static final String MARKER_FULL = MARKER + " (do not remove)";
    public static final String SCRIPTS_ROOT = "kubejs/server_scripts/";

    private ScriptWriter() {}

    public sealed interface DumpResult {
        Path path();
        String message();

        record Success(Path path) implements DumpResult {
            @Override public String message() { return "Dumped to: " + path; }
        }
        record Fallback(Path path, String reason) implements DumpResult {
            @Override public String message() { return "Fallback (" + reason + "); created: " + path; }
        }
        record Failure(String message) implements DumpResult {
            @Override public Path path() { return null; }
        }
    }

    public static DumpResult dump(RecipeDraft draft, String recipeId) {
        String code = draft.emit(recipeId);
        if (code == null || code.isBlank()) {
            return new DumpResult.Failure("Draft is empty (need at least output + relevant inputs)");
        }
        Path target = Minecraft.getInstance().gameDirectory.toPath()
            .resolve(SCRIPTS_ROOT + draft.relativeOutputPath());
        try {
            Files.createDirectories(target.getParent());
            if (!Files.exists(target)) {
                writeNewFile(target, draft, code);
                return new DumpResult.Success(target);
            }
            return appendIntoExisting(target, draft, code);
        } catch (IOException e) {
            Credit.LOGGER.error("[CraftPattern] dump IO error", e);
            return new DumpResult.Failure("IO error: " + e.getMessage());
        }
    }

    private static void writeNewFile(Path target, RecipeDraft draft, String code) throws IOException {
        String now = LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
        String header =
            "// =====================================================\n" +
            "// Generated by /craftpattern (credit MOD)\n" +
            "// FORMAT: KubeJS (https://kubejs.com/)\n" +
            "// Category: " + draft.recipeType().getUid() + "\n" +
            "// First created: " + now + "\n" +
            "// Place this file under kubejs/server_scripts/ to take effect.\n" +
            "// Run /reload (or /kubejs reload server_scripts) to apply.\n" +
            "// =====================================================\n\n" +
            "ServerEvents.recipes(event => {\n\n";
        String footer =
            "    " + MARKER_FULL + "\n" +
            "});\n";
        Files.writeString(target, header + code + footer);
    }

    private static DumpResult appendIntoExisting(Path target, RecipeDraft draft, String code) throws IOException {
        String content = Files.readString(target);

        Integer insertAt = findMarkerInsertionPoint(content);
        String reason = null;
        if (insertAt == null) {
            insertAt = findClosingBraceInsertionPoint(content);
            reason = "marker missing";
        }
        if (insertAt != null) {
            String newContent = content.substring(0, insertAt) + code + content.substring(insertAt);
            Files.writeString(target, newContent);
            return reason == null
                ? new DumpResult.Success(target)
                : new DumpResult.Fallback(target, reason);
        }

        // Final fallback: create a numbered new file
        Path numbered = nextNumberedFile(target);
        writeNewFile(numbered, draft, code);
        return new DumpResult.Fallback(numbered, "no marker and no `});` found");
    }

    @Nullable
    private static Integer findMarkerInsertionPoint(String content) {
        int idx = content.indexOf(MARKER);
        if (idx < 0) return null;
        return content.lastIndexOf('\n', idx) + 1;
    }

    @Nullable
    private static Integer findClosingBraceInsertionPoint(String content) {
        int idx = content.lastIndexOf("});");
        if (idx < 0) return null;
        return content.lastIndexOf('\n', idx) + 1;
    }

    private static Path nextNumberedFile(Path original) {
        String fileName = original.getFileName().toString();
        int dot = fileName.lastIndexOf('.');
        String base = dot >= 0 ? fileName.substring(0, dot) : fileName;
        String ext  = dot >= 0 ? fileName.substring(dot)    : "";
        Path dir = original.getParent();
        for (int i = 2; i < 10000; i++) {
            Path candidate = dir.resolve(base + "_" + i + ext);
            if (!Files.exists(candidate)) return candidate;
        }
        return dir.resolve(base + "_overflow" + ext);
    }
}